/*
 * VIEWS
 *
*/

CREATE VIEW EM.OVERVIEW AS
	SELECT EM.EVENTO.nome, EM.EVENTO.dataini, EM.EVENTO.numdias, EM.EVENTO.numbilhetes, EM.PROMOTOR.nome AS PROMOTOR, EM.BANDA.nome AS BANDA, EM.CONCERTO.datatimeini AS horainicio, EM.CONCERTO.duracao
	FROM     EM.PROMOTOR INNER JOIN
					  EM.EVENTO ON EM.PROMOTOR.numCC = EM.EVENTO.cc_promotor INNER JOIN
					  EM.CONCERTO ON EM.EVENTO.id = EM.CONCERTO.id_evento INNER JOIN
					  EM.BANDA ON EM.CONCERTO.id_banda = EM.BANDA.id

SELECT * FROM EM.OVERVIEW